name: 台股交叉策略自動推播

on:
  schedule:
    - cron: '0 10 * * *'  # 台灣時間 18:00 = UTC 10:00
  workflow_dispatch:

jobs:
  run-cross-strategy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pandas requests python-telegram-bot==13.15

      - name: Run Strategy Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
